"""Operational briefing model.

The Overview and the module pages answer "what is happening right now". This
answers the three questions actually asked in a briefing:

    what matters right now · what changed recently · what should I be watching

`build_briefing_snapshot()` returns a plain data structure. It contains no Dash
components and no reportlab flowables, because BOTH the `/briefing` screen and
the briefing PDF render from it — one set of operational statements, so the
printed pack can never disagree with the screen it was generated from.

Two rules this module is built around:

* **Nothing here is generated by a language model.** Every sentence is
  assembled from stored values by fixed rules, so the same data always produces
  the same briefing and every number is traceable to a row in the database.
* **Derived information is labelled as derived.** Observations, official
  warnings and Passive Monitor's own extrapolations are separate types with
  separate rendering, and a projected flood ETA is never presented as a BoM
  forecast.

`as_of` exists so a briefing is not welded to `datetime.now()`. It sets the
reference clock for the change window and for freshness. Reconstructing the
*state* sections at a past moment needs the Phase C state journal, so until
then a snapshot reports `state_is_live=True` and the UI says so rather than
implying the KPIs are historical.
"""
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta

import pandas as pd

from app import database, intel_feed
from app.config import load_config
from app.modules.fire import data as fire_data
from app.modules.flood import data as flood_data
from app.modules.flood import trend as flood_trend
from app.modules.power import data as power_data
from app.modules.roads import data as roads_data
from app.modules.storm import data as storm_data
from app.modules.weather import data as weather_data

log = logging.getLogger(__name__)

# Selectable "changes since" periods. 1 hour is the default: long enough to
# cover the gap between briefings, short enough that everything in it is still
# operationally live.
WINDOW_OPTIONS = [(30, "30 minutes"), (60, "1 hour"), (180, "3 hours"),
                  (360, "6 hours"), (720, "12 hours")]
DEFAULT_WINDOW_MINUTES = 60

# A source is flagged when it hasn't produced a cycle in this multiple of its
# own configured interval — so a 15-minute collector isn't called stale at 3
# minutes and an every-minute one isn't allowed to sit dead for an hour.
STALE_INTERVAL_MULTIPLE = 3
# ...with a floor, so a fast collector doesn't flap on one slow cycle.
STALE_FLOOR_MINUTES = 10

# Watch-point trigger: a gauge this close to its next threshold is worth
# naming even though it hasn't crossed it.
WATCH_DISTANCE_M = 0.5
# An AWS gust at or above this is called out as notable. Chosen to sit near the
# top of the network's normal range; it is OUR reporting threshold, not a
# warning criterion, and is described that way wherever it appears.
WATCH_GUST_KMH = 70

OBSERVED, PROJECTION = "observed", "projection"

VICEMERGENCY_LEVELS = ("Emergency Warning", "Watch and Act", "Advice")
# Emergency Warnings and Watch & Acts are always listed in full; Advices are
# capped at this many (see _warnings).
ADVICE_LIMIT = 5


# --------------------------------------------------------------------------- #
# Model
# --------------------------------------------------------------------------- #
@dataclass
class Kpi:
    """One headline figure. `value` is pre-formatted, "—" when unknown, so the
    screen and the PDF can never format the same number two different ways.

    `detail` carries the reading's location as a SEPARATE field rather than
    baked into the value: an extreme is meaningless without its station, but
    "78 km/h — Wilsons Promontory" set as one string wraps a KPI card onto
    three lines. Each surface joins them the way it can lay them out.
    """
    label: str
    value: str
    group: str
    accent: str = None
    alert: bool = False
    detail: str = None

    @property
    def full_value(self):
        """Value and location as one string, for text and table rendering."""
        return "%s — %s" % (self.value, self.detail) if self.detail else self.value


@dataclass
class Change:
    """A detected change from the Intelligence Feed, inside the window."""
    ts: datetime
    time: str
    headline: str
    lines: list
    severity: int
    severity_label: str
    hazard: str
    hazard_label: str
    entity_name: str
    url: str


@dataclass
class Warning:
    """An active warning. `source` separates the two authorities — VicEmergency
    community warnings and BoM warning products are not interchangeable.

    `level` is only set for VicEmergency, where Emergency Warning / Watch and
    Act / Advice is the meaningful split. BoM's `group_type` is deliberately
    NOT surfaced as a level: it reads as minor/moderate/major and would be
    mistaken for the flood gauge classification, which is a different scale
    entirely (the Weather page omits it for the same reason). BoM warnings are
    separated by warning TYPE instead, which is what they are actually chosen
    by; group_type still drives the ordering.
    """
    source: str
    kind: str
    title: str
    level: str = None
    location: str = ""
    action: str = None
    issued: datetime = None
    expires: datetime = None
    url: str = None


@dataclass
class Consequence:
    """A cross-layer situation: several facts about one place that are more
    significant together than apart. Assembled by rule from stored data."""
    title: str
    lines: list
    hazard: str = None
    url: str = None


@dataclass
class WatchPoint:
    """Something that has not triggered the most severe threshold but deserves
    attention. `kind` is OBSERVED or PROJECTION and must survive into the UI —
    an extrapolated ETA has to look different from a measurement."""
    title: str
    lines: list
    kind: str = OBSERVED
    url: str = None


@dataclass
class SourceStatus:
    name: str
    last_update: datetime = None
    age_minutes: float = None
    state: str = "ok"          # ok | stale | never
    detail: str = None

    @property
    def is_healthy(self):
        return self.state == "ok"


@dataclass
class BriefingSnapshot:
    generated_at: datetime
    as_of: datetime
    window_minutes: int
    window_label: str
    window_start: datetime
    situation: list = field(default_factory=list)
    changes: list = field(default_factory=list)
    warnings: list = field(default_factory=list)
    consequences: list = field(default_factory=list)
    watch_points: list = field(default_factory=list)
    weather: list = field(default_factory=list)
    sources: list = field(default_factory=list)
    # Advice-level VicEmergency warnings not listed (see ADVICE_LIMIT).
    omitted_advice: int = 0
    # False would mean the state sections were reconstructed for `as_of`;
    # until the Phase C journal exists they are always live.
    state_is_live: bool = True

    @property
    def generated_label(self):
        return self.generated_at.strftime("%d %b %Y %H:%M")

    @property
    def stale_sources(self):
        return [s for s in self.sources if not s.is_healthy]

    def warnings_from(self, source):
        return [w for w in self.warnings if w.source == source]

    @property
    def has_content(self):
        return bool(self.changes or self.warnings or self.consequences
                    or self.watch_points)


# --------------------------------------------------------------------------- #
# Formatting (shared by the screen and the PDF so they cannot drift)
# --------------------------------------------------------------------------- #
def _count(value):
    return "—" if value is None else "{:,}".format(int(value))


def _number(value, fmt="{:.1f}", unit=""):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "—"
    try:
        text = fmt.format(float(value))
    except (TypeError, ValueError):
        return "—"
    if not unit:
        return text
    return text + unit if unit == "%" else text + " " + unit


def _plural(n, singular, plural=None):
    return "%d %s" % (n, singular if n == 1 else (plural or singular + "s"))


def _as_datetime(value):
    if value is None or isinstance(value, datetime):
        return value
    ts = pd.to_datetime(value, errors="coerce")
    return None if pd.isna(ts) else ts.to_pydatetime()


def _age_minutes(then, now):
    if then is None:
        return None
    return max(0.0, (now - then).total_seconds() / 60.0)


def describe_age(minutes):
    """"4 min ago" / "2 hr 10 min ago" / "never" — one wording everywhere."""
    if minutes is None:
        return "never"
    if minutes < 1:
        return "just now"
    if minutes < 90:
        return "%d min ago" % int(round(minutes))
    hours, mins = divmod(int(round(minutes)), 60)
    return "%d hr %d min ago" % (hours, mins) if mins else "%d hr ago" % hours


def window_label(minutes):
    for value, label in WINDOW_OPTIONS:
        if value == minutes:
            return label
    return "%d minutes" % minutes


# --------------------------------------------------------------------------- #
# Section 1 — current situation
# --------------------------------------------------------------------------- #
def _situation(cfg):
    """Headline KPIs across every module.

    Warning levels are deliberately NOT summed. "3 warnings" is not an
    operational fact — one Emergency Warning and two Advices need different
    responses, and a combined figure lets either one misrepresent the other.
    """
    kpis = []

    totals = power_data.latest_totals() or {}
    off = totals.get("customers_off")
    high = cfg["alerts"]["high_customers_off"]
    kpis.append(Kpi("Customers Without Power", _count(off), "Power", "#7048e8",
                    alert=bool(off is not None and off > high)))

    flood = flood_data.flooding_breakdown()
    kpis += [
        Kpi("Gauges ≥ Minor", str(flood["minor"]), "Flood", "#e6c700",
            alert=bool(flood["minor"])),
        Kpi("Gauges ≥ Moderate", str(flood["moderate"]), "Flood", "#ff7f0e",
            alert=bool(flood["moderate"])),
        Kpi("Gauges ≥ Major", str(flood["major"]), "Flood", "#d62728",
            alert=bool(flood["major"])),
    ]

    fire = fire_data.latest_counts()
    kpis += [
        Kpi("Active Fires", str(fire["active_fires"]), "Fire", "#ff5722",
            alert=bool(fire["active_fires"])),
        Kpi("Emergency Warnings", str(fire["emergency"]), "Fire", "#d62728",
            alert=bool(fire["emergency"])),
        Kpi("Watch & Act", str(fire["watch_act"]), "Fire", "#ff7f0e",
            alert=bool(fire["watch_act"])),
    ]

    bom = weather_data.warning_counts()
    kpis.append(Kpi("Active BoM Warnings", str(bom["total"]), "Weather",
                    "#1f77b4", alert=bool(bom["total"])))

    roads = roads_data.latest_counts()
    kpis += [
        Kpi("Road Disruptions", str(roads["total"]), "Roads", "#ff7f0e"),
        Kpi("Full Closures", str(roads["closures"]), "Roads", "#d62728",
            alert=bool(roads["closures"])),
    ]

    storm = storm_data.latest_counts()
    kpis.append(Kpi("Storm Cells (mod/strong)",
                    str(storm["strong"] + storm["moderate"]), "Storm",
                    "#d62728", alert=bool(storm["strong"])))

    aws = weather_data.aws_weather_summary()
    wettest = aws.get("wettest")
    kpis.append(Kpi("Wettest Station (since 9am)",
                    _number(wettest["value"], "{:.1f}", "mm") if wettest else "—",
                    "Rain", "#1f77b4",
                    detail=wettest["station"] if wettest else None))
    return kpis


# --------------------------------------------------------------------------- #
# Section 2 — significant changes
# --------------------------------------------------------------------------- #
def _changes(window_start, as_of, min_severity=intel_feed.NOTABLE, limit=40):
    """Detected changes inside the window, from the Intelligence Feed.

    Ordered by severity band first, then newest-first inside each band: at a
    briefing the critical thing that happened 40 minutes ago outranks the
    notable thing that happened 2 minutes ago. Info-level entries are excluded —
    the briefing is for what matters, and the full feed remains one click away.

    `with_context=False` on purpose. The feed appends proximity context to
    every entry, which is right on a feed but would put the same fact under two
    headings here — cross-layer material belongs in Emerging Consequences, so a
    change keeps only what it measured: the delta, the rate and its own detail.
    """
    try:
        raw = intel_feed.entries(since=window_start, until=as_of,
                                 min_severity=min_severity, limit=limit,
                                 with_context=False)
    except Exception:
        log.exception("Briefing: Intelligence Feed unavailable")
        return []
    changes = [Change(
        ts=e["ts"], time=e["time"], headline=e["headline"], lines=e["lines"],
        severity=e["severity"], severity_label=e["severity_label"],
        hazard=e["hazard"], hazard_label=e["hazard_label"],
        entity_name=e["entity_name"], url=e["url"]) for e in raw]
    changes.sort(key=lambda c: (-c.severity, -(c.ts.timestamp() if c.ts else 0)))
    return changes


# --------------------------------------------------------------------------- #
# Section 3 — active warnings
# --------------------------------------------------------------------------- #
def _warnings():
    """Active warnings from both authorities, most severe first within each.

    Returns `(warnings, omitted_advice)`. Warning bodies are deliberately not
    carried: a briefing screen needs the what/where/when and a link, not
    several pages of BoM prose.

    Advice-level VicEmergency warnings are capped. During a widespread flood
    event there are routinely dozens of them, all saying "Stay Informed", and
    printing every one pushes the Emergency Warnings off the page — the exact
    failure a briefing exists to prevent. The omitted count is returned so the
    briefing states plainly how many it didn't list.
    """
    out = []
    try:
        fires = fire_data.active_incidents(warnings_only=True)
    except Exception:
        log.exception("Briefing: VicEmergency warnings unavailable")
        fires = pd.DataFrame()
    omitted_advice = 0
    if not fires.empty:
        order = {level: i for i, level in enumerate(VICEMERGENCY_LEVELS)}
        fires = fires.copy()
        fires["_prio"] = fires["warning_level"].map(
            lambda v: order.get(str(v or "").strip(), len(order)))
        fires = fires[fires["_prio"] < len(order)].sort_values(
            ["_prio", "updated"], ascending=[True, False])
        advice_seen = 0
        for _, r in fires.iterrows():
            level = str(r["warning_level"]).strip()
            if level == "Advice":
                advice_seen += 1
                if advice_seen > ADVICE_LIMIT:
                    omitted_advice += 1
                    continue
            out.append(Warning(
                source="VicEmergency",
                level=level,
                # `headline` on a VicEmergency warning is just the level again
                # ("Advice"); the useful pair is the event and where it is.
                kind=(r.get("event") or r.get("category2")
                      or r.get("category1") or "Incident"),
                title=r.get("location") or r.get("headline") or "Warning",
                location=r.get("location") or "",
                action=r.get("action") or None,
                issued=_as_datetime(r.get("created")),
                url="/fire"))

    try:
        bom = weather_data.active_warnings()
    except Exception:
        log.exception("Briefing: BoM warnings unavailable")
        bom = pd.DataFrame()
    for _, r in bom.iterrows():
        out.append(Warning(
            source="BoM",
            kind=r.get("type_label") or "Warning",
            title=r.get("title") or "",
            issued=_as_datetime(r.get("issue_time")),
            expires=_as_datetime(r.get("expiry_time")),
            url="/weather/warning/%s" % r.get("warning_id")))
    return out, omitted_advice


# --------------------------------------------------------------------------- #
# Section 4 — emerging consequences
# --------------------------------------------------------------------------- #
def _consequences(cfg, changes, limit=6):
    """Places where SEVERAL layers are saying something at once.

    A consequence is not "a change, plus its surroundings" — that is just the
    change, and the Intelligence Feed already renders it that way. It is a
    location where changes from two or more different hazards landed inside the
    context radius during the window: a gauge crossing Moderate is a flood fact,
    but a gauge crossing Moderate *while* the highway beside it closes *and* the
    town loses power is a situation, and it is the second thing a briefing
    exists to surface.

    So: cluster the significant changes geographically, keep clusters spanning
    more than one hazard, and add the standing cross-layer context underneath.
    Entirely deterministic — same data in, same wording out, every line
    traceable to a stored row.
    """
    if not changes:
        return []
    radius = float(cfg["intel"]["context_radius_km"])
    try:
        sources = intel_feed._context_sources()
    except Exception:
        log.exception("Briefing: cross-layer context unavailable")
        return []

    located = []
    for change in changes:
        if change.severity < intel_feed.MAJOR:
            continue
        lat, lon = _entity_position(change)
        if lat is not None and lon is not None:
            located.append((change, lat, lon))
    if not located:
        return []

    # Greedy clustering, most severe change first, so each cluster is anchored
    # on the worst thing in it rather than on whatever was read first.
    located.sort(key=lambda item: (-item[0].severity,
                                   -(item[0].ts.timestamp() if item[0].ts else 0)))
    clusters = []
    for change, lat, lon in located:
        for cluster in clusters:
            if intel_feed._haversine_km(cluster["lat"], cluster["lon"],
                                        lat, lon) <= radius:
                cluster["members"].append(change)
                break
        else:
            clusters.append({"lat": lat, "lon": lon, "members": [change]})

    out = []
    for cluster in clusters:
        if len(out) >= limit:
            break
        members = cluster["members"]
        if len({m.hazard for m in members}) < 2:
            continue  # single-hazard: the change already says it all
        lines = []
        for member in members:
            if member.headline not in lines:
                lines.append(member.headline)
        # Standing context underneath. hazard="" so nothing is skipped: at a
        # multi-hazard location every layer is relevant, including the ones the
        # per-hazard feed view would have suppressed as "itself".
        for line in intel_feed._nearby_lines(cluster["lat"], cluster["lon"],
                                             radius, sources, ""):
            if line not in lines:
                lines.append(line)
        primary = members[0]
        out.append(Consequence(
            title=primary.entity_name or primary.headline,
            lines=lines, hazard=primary.hazard, url=primary.url))
    return out


def _entity_position(change):
    """Coordinates for a change, from the intel_events row that produced it."""
    df = database.read_df(
        "SELECT latitude, longitude FROM intel_events "
        "WHERE hazard = ? AND headline = ? AND latitude IS NOT NULL "
        "ORDER BY ts DESC LIMIT 1", [change.hazard, change.headline])
    if df.empty:
        return None, None
    row = df.iloc[0]
    lat = pd.to_numeric(row["latitude"], errors="coerce")
    lon = pd.to_numeric(row["longitude"], errors="coerce")
    return (None if pd.isna(lat) else float(lat),
            None if pd.isna(lon) else float(lon))


# --------------------------------------------------------------------------- #
# Section 5 — watch points
# --------------------------------------------------------------------------- #
def _watch_points(cfg, aws_summary, limit=8):
    """Conditions short of the worst threshold that still deserve attention.

    Every entry declares whether it is an OBSERVED value or a PROJECTION, and
    projections carry the trend engine's own disclaimer — an extrapolated ETA
    must never read as an official forecast.
    """
    out = []
    out += _flood_watch_points(cfg)
    out += _storm_watch_points()
    out += _gust_watch_points(aws_summary)
    return out[:limit]


def _flood_watch_points(cfg):
    """Gauges rising toward, but not yet at, their next threshold."""
    out = []
    try:
        gauges = flood_data.map_gauges()
    except Exception:
        log.exception("Briefing: flood gauges unavailable")
        return out
    if gauges.empty:
        return out
    # Only gauges already flooding or close to it are worth analysing — the
    # trend engine is far too expensive to run over the whole network.
    candidates = gauges[gauges["priority"] < 4]["station_name"].tolist()[:12]
    for name in candidates:
        key = str(name).strip().lower()
        try:
            analysis = flood_trend.analyse(key, cfg=cfg)
        except Exception:
            log.exception("Briefing: flood trend failed for %s", key)
            continue
        if not analysis or analysis.get("distance_m") is None:
            continue
        distance = analysis["distance_m"]
        rate = analysis.get("rate_m_hr")
        if distance > WATCH_DISTANCE_M or not rate or rate <= 0:
            continue
        lines = ["%s below %s · rising %s" % (
            _number(distance, "{:.2f}", "m"),
            str(analysis.get("target_name") or "next threshold").title(),
            _number(rate, "{:+.2f}", "m/hr"))]
        eta = analysis.get("eta_point")
        kind = OBSERVED
        if eta:
            kind = PROJECTION
            lines.append("Projected to reach %s about %s%s" % (
                str(analysis.get("target_name") or "").title(),
                eta.strftime("%H:%M"),
                (" (%s–%s)" % (analysis["eta_early"].strftime("%H:%M"),
                               analysis["eta_late"].strftime("%H:%M")))
                if analysis.get("eta_early") and analysis.get("eta_late") else ""))
            lines.append(flood_trend.DISCLAIMER)
        out.append(WatchPoint(title=str(name), lines=lines, kind=kind,
                              url="/flood"))
    return out


def _storm_watch_points():
    """Moderate/strong cells, with their measured movement."""
    out = []
    try:
        cells = storm_data.active_cells()
    except Exception:
        log.exception("Briefing: storm cells unavailable")
        return out
    if cells.empty:
        return out
    cells = cells[cells["classification"].isin(["strong", "moderate"])]
    for _, r in cells.head(4).iterrows():
        bits = [str(r.get("classification") or "").title()]
        speed = pd.to_numeric(r.get("speed_kmh"), errors="coerce")
        bearing = pd.to_numeric(r.get("bearing_deg"), errors="coerce")
        if not pd.isna(speed) and not pd.isna(bearing):
            bits.append("%s at %s" % (intel_feed._cardinal(float(bearing)),
                                      _number(speed, "{:.0f}", "km/h")))
        area = pd.to_numeric(r.get("area_km2"), errors="coerce")
        if not pd.isna(area):
            bits.append("~%s" % _number(area, "{:.0f}", "km²"))
        out.append(WatchPoint(title="Storm cell %s" % r.get("cell_id"),
                              lines=[" · ".join(bits)], kind=OBSERVED,
                              url="/storm"))
    return out


def _gust_watch_points(aws_summary):
    """Unusually strong AWS gusts. An observation, not a warning threshold."""
    gusts = [g for g in (aws_summary.get("top_gusts") or [])
             if g["value"] >= WATCH_GUST_KMH]
    if not gusts:
        return []
    return [WatchPoint(
        title="Strong wind gusts observed",
        lines=["%s — %s" % (g["station"], _number(g["value"], "{:.0f}", "km/h"))
               for g in gusts]
        + ["Raw AWS observations at or above %d km/h. Passive Monitor's "
           "reporting threshold, not a warning criterion." % WATCH_GUST_KMH],
        kind=OBSERVED, url="/weather")]


# --------------------------------------------------------------------------- #
# Section 6 — weather observations
# --------------------------------------------------------------------------- #
def _weather(aws_summary):
    """The AWS headline values from Phase A."""
    out = []

    def add(label, entry, fmt, unit, suffix=None):
        if not entry:
            out.append(Kpi(label, "—", "Weather"))
            return
        detail = entry["station"]
        if suffix and entry.get(suffix):
            detail += " (%s)" % entry[suffix]
        out.append(Kpi(label, _number(entry["value"], fmt, unit), "Weather",
                       detail=detail))

    add("Strongest current gust", aws_summary.get("strongest_gust"), "{:.0f}", "km/h")
    add("Lowest relative humidity", aws_summary.get("lowest_humidity"), "{:.0f}", "%")
    add("Wettest since 9am", aws_summary.get("wettest"), "{:.1f}", "mm")
    add("Highest gust today", aws_summary.get("max_daily_gust"), "{:.0f}", "km/h",
        suffix="max_gust_time")
    return out


# --------------------------------------------------------------------------- #
# Section 7 — data freshness
# --------------------------------------------------------------------------- #
def _last_timestamp(sql):
    df = database.read_df(sql)
    if df.empty:
        return None
    return _as_datetime(df.iloc[0]["last"])


def _sources(cfg, now):
    """Per-collector last-cycle time and staleness.

    A briefing must never let old data look current, so every source reports
    even when it has never run — silence is itself the finding.
    """
    def minutes(section, key="interval_minutes", default=15):
        try:
            return float(cfg[section][key])
        except (KeyError, TypeError, ValueError):
            return float(default)

    power_interval = minutes("power", "interval_seconds", 300) / 60.0
    specs = [
        ("Flood", lambda: flood_data.heartbeat_summary()[1], minutes("flood")),
        ("VicEmergency", lambda: fire_data.heartbeat_summary()[1], minutes("fire")),
        ("BoM Weather", lambda: weather_data.heartbeat_summary()[1], minutes("weather")),
        ("AWS", lambda: _last_timestamp(
            "SELECT MAX(timestamp) AS last FROM rainfall_aws"), minutes("rainfall")),
        ("Roads", lambda: roads_data.heartbeat_summary()[1], minutes("roads")),
        ("Power", lambda: _last_timestamp(
            "SELECT MAX(timestamp) AS last FROM power_timeseries"), power_interval),
        ("Storm", lambda: storm_data.heartbeat_summary()[1], minutes("storm")),
    ]

    out = []
    for name, get_last, interval in specs:
        try:
            last = _as_datetime(get_last())
        except Exception:
            log.exception("Briefing: freshness check failed for %s", name)
            out.append(SourceStatus(name, state="never",
                                    detail="status unavailable"))
            continue
        age = _age_minutes(last, now)
        if last is None:
            out.append(SourceStatus(name, state="never",
                                    detail="no cycle recorded"))
            continue
        limit = max(STALE_FLOOR_MINUTES, interval * STALE_INTERVAL_MULTIPLE)
        state = "stale" if age is not None and age > limit else "ok"
        detail = None
        if state == "stale":
            detail = "expected every %g min" % interval
        out.append(SourceStatus(name, last_update=last, age_minutes=age,
                                state=state, detail=detail))
    return out


# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #
def build_briefing_snapshot(as_of=None, window_minutes=DEFAULT_WINDOW_MINUTES,
                            cfg=None):
    """Assemble the whole briefing.

    `as_of=None` means live. Every section degrades on its own: a module that
    errors contributes nothing and is reported as stale rather than taking the
    briefing down with it.
    """
    cfg = cfg or load_config()
    now = datetime.now()
    as_of = as_of or now
    window_minutes = int(window_minutes or DEFAULT_WINDOW_MINUTES)
    window_start = as_of - timedelta(minutes=window_minutes)

    def safe(label, fn, default):
        try:
            return fn()
        except Exception:
            log.exception("Briefing: %s section failed", label)
            return default

    aws_summary = safe("weather observations",
                       weather_data.aws_weather_summary, {})
    changes = safe("significant changes",
                   lambda: _changes(window_start, as_of), [])
    warnings, omitted_advice = safe("active warnings", _warnings, ([], 0))
    return BriefingSnapshot(
        generated_at=now,
        as_of=as_of,
        window_minutes=window_minutes,
        window_label=window_label(window_minutes),
        window_start=window_start,
        situation=safe("current situation", lambda: _situation(cfg), []),
        changes=changes,
        warnings=warnings,
        omitted_advice=omitted_advice,
        consequences=safe("emerging consequences",
                          lambda: _consequences(cfg, changes), []),
        watch_points=safe("watch points",
                          lambda: _watch_points(cfg, aws_summary), []),
        weather=safe("weather observations", lambda: _weather(aws_summary), []),
        sources=safe("data freshness", lambda: _sources(cfg, now), []),
    )


# --------------------------------------------------------------------------- #
# Plain-text rendering (the "copy briefing" button, and a readable fallback)
# --------------------------------------------------------------------------- #
def briefing_text(snapshot):
    """The whole briefing as plain text, for pasting into a log or a message."""
    lines = ["WATCHDESK OPERATIONAL BRIEFING",
             "Generated %s" % snapshot.generated_label,
             "Changes since: last %s" % snapshot.window_label, ""]

    lines.append("CURRENT SITUATION")
    for kpi in snapshot.situation:
        lines.append("  %-28s %s" % (kpi.label, kpi.full_value))
    lines.append("")

    lines.append("SIGNIFICANT CHANGES (last %s)" % snapshot.window_label)
    if snapshot.changes:
        for change in snapshot.changes:
            lines.append("  %s  [%s] %s" % (change.time, change.severity_label,
                                            change.headline))
            for line in change.lines:
                lines.append("      %s" % line)
    else:
        lines.append("  No significant changes detected in this period.")
    lines.append("")

    for source in ("VicEmergency", "BoM"):
        active = snapshot.warnings_from(source)
        lines.append("ACTIVE WARNINGS — %s" % source.upper())
        if active:
            for w in active:
                stamp = w.issued.strftime("%d %b %H:%M") if w.issued else "—"
                expiry = (" · expires %s" % w.expires.strftime("%d %b %H:%M")
                          if w.expires else "")
                prefix = "[%s] " % w.level if w.level else ""
                lines.append("  %s%s — %s (issued %s%s)" % (
                    prefix, w.kind, w.title, stamp, expiry))
        else:
            lines.append("  None active.")
        if source == "VicEmergency" and snapshot.omitted_advice:
            lines.append("  ... and %s not listed."
                         % _plural(snapshot.omitted_advice, "further Advice warning"))
        lines.append("")

    lines.append("EMERGING CONSEQUENCES")
    if snapshot.consequences:
        for c in snapshot.consequences:
            lines.append("  %s" % c.title)
            for line in c.lines:
                lines.append("      %s" % line)
    else:
        lines.append("  No significant cross-layer consequences currently identified.")
    lines.append("")

    lines.append("WATCH POINTS")
    if snapshot.watch_points:
        for w in snapshot.watch_points:
            tag = "PROJECTION" if w.kind == PROJECTION else "OBSERVED"
            lines.append("  [%s] %s" % (tag, w.title))
            for line in w.lines:
                lines.append("      %s" % line)
    else:
        lines.append("  Nothing currently approaching a threshold.")
    lines.append("")

    lines.append("WEATHER OBSERVATIONS")
    for kpi in snapshot.weather:
        lines.append("  %-28s %s" % (kpi.label, kpi.full_value))
    lines.append("  Raw BoM automatic weather station observations — not "
                 "quality-controlled, not an official warning product.")
    lines.append("")

    lines.append("DATA FRESHNESS")
    for s in snapshot.sources:
        flag = "" if s.is_healthy else "   <-- CHECK"
        lines.append("  %-14s %s%s" % (s.name, describe_age(s.age_minutes), flag))
    return "\n".join(lines)
